name = priviledges_manager
title = Privileges Manager
description = A visual, searchable GUI to manage player privileges with toggle switches. Works on Minetest Game and Mineclonia/VoxeLibre, and can manage offline players.
author = jamesdavidclarke
optional_depends = sfinv, unified_inventory
supported_games = voxelibre, mineclone2, mineclonia, minetest_game
min_minetest_version = 5.4
